name = 'not-much-lav'
license = 'MIT'
licenselink = 'https://github.com/imgios/not-much/blob/main/LICENSE'
description = 'A modified version of the Hugo theme not-much'

homepage = 'https://github.com/imgios/not-much'

demosite = 'https://giosuesulipano.it/not-much/'

tags = ['blog', 'website', 'simple', 'dark', 'minimal', 'responsive']

features = ['blog', 'reponsive', 'theme-palettes']

[author]
  name = 'laven-dev'
  homepage = 'https://laven.dev'
